package net.bounceme.dur.nntp.view;

import java.util.logging.Logger;
import net.bounceme.dur.nntp.controller.Usenet;

public class Main extends java.awt.Frame {

    private final static Logger LOG = Logger.getLogger(Main.class.getName());
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        overview = new net.bounceme.dur.nntp.view.Overview();
        detail = new net.bounceme.dur.nntp.view.Detail();
        groups = new net.bounceme.dur.nntp.view.Groups();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTabbedPane1.addTab("tab1", overview);
        jTabbedPane1.addTab("tab2", detail);

        groups.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                groupsPropertyChange(evt);
            }
        });
        jTabbedPane1.addTab("tab3", groups);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName("overview");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void groupsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_groupsPropertyChange
        LOG.fine("prp chg "+ evt.getNewValue().toString());
    }//GEN-LAST:event_groupsPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detail;
    private javax.swing.JPanel groups;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel overview;
    // End of variables declaration//GEN-END:variables
}
